
image: docker

stages:
  - build

build:
  only:
    - main
    - preprod
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker build --tag $CI_REGISTRY_IMAGE/doc:$CI_COMMIT_REF_NAME ./doc/
    - docker push $CI_REGISTRY_IMAGE/doc:$CI_COMMIT_REF_NAME
